name: Python App CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Configurazione Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' 

    - name: Installazione dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verifica sintassi (Linting)
      run: |
        python -m py_compile Np_Zero_2.0.0.py

    - name: Creazione Eseguibile (Build)
      run: |
        pyinstaller -F -w --hidden-import pypdf --hidden-import openpyxl --name "GestioneNuoviPrezzi" Np_Zero_2.0.0.py

    - name: Archiviazione Artefatto
      uses: actions/upload-artifact@v4
      with:
        name: Applicazione-Windows
        path: dist/GestioneNuoviPrezzi.exe
